name: quan-ly-nhan-su

services:
  db-dev:
    image: postgres:18-alpine
    container_name: quan-ly-nhan-su-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-thisisapassword}
      POSTGRES_DB: ${DATABASE_DB:-test_fastapi_dev}
    volumes:
      - quan-ly-nhan-su-db-dev-data:/var/lib/postgresql/18/data
    ports:
      - "${DATABASE_PORT:-5433}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_DB:-test_fastapi_dev}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  quan-ly-nhan-su-db-dev-data:
