name: test-fastapi

services:
  api:
    container_name: test-fastapi-api
    build:
      context: ..
      dockerfile: docker/dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-thisisapassword}@db:5432/${DATABASE_DB:-test_fastapi}
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY:-change-this-secret-key-to-32-bytes-minimum}
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-fastapi-network

  db:
    image: postgres:18-alpine
    container_name: test-fastapi-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-thisisapassword}
      POSTGRES_DB: ${DATABASE_DB:-test_fastapi}
    volumes:
      - test-fastapi-db-data:/var/lib/postgresql/18/data
    networks:
      - test-fastapi-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_DB:-test_fastapi}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  test-fastapi-db-data:

networks:
  test-fastapi-network:
    driver: bridge
